FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends         python3-dev gcc i2c-tools         && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY drivers.json ./drivers.json

CMD ["python", "app.py"]
