FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY script.js /usr/share/nginx/html/script.js
COPY driver.html /usr/share/nginx/html/driver.html
COPY driver.js /usr/share/nginx/html/driver.js
COPY simulation.js /usr/share/nginx/html/simulation.js
COPY route-simulation.js /usr/share/nginx/html/route-simulation.js
COPY livemap.html /usr/share/nginx/html/livemap.html
